analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6633786526508629
  brandStrength: 0.2048984
  lightness: 0.3068598345853388
  brandColors:
    - '#6F99BD'
    - '#26383C'
    - '#6B7880'
    - '#0C0F16'
    - '#975E58'
  rhythmicContrast: 0.7510770636145025
typography_spectrum: 0.7688171
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.4247312
favicon: null
name: Teacher Nick Thailand
